package app.tree.shared

/** Texts of bots (wave 5), merged into [Strings]. */
internal object BotStrings {
    val ko = mapOf(
        "bots" to "봇",
        "bot_badge" to "봇",
        "bot_factory" to "봇 만들기",
        "bot_factory_note" to "Tree는 봇을 실행하지 않습니다. 봇은 만든 사람이 자기 서버에서 봇 게이트웨이로 실행합니다. 게이트웨이를 운영하는 사람은 봇이 받는 모든 메시지를 읽습니다.",
        "bot_username" to "봇 사용자 이름 (bot으로 끝남)",
        "bot_create" to "만들기",
        "bot_token" to "봇 토큰",
        "bot_token_note" to "이 토큰은 지금 한 번만 보입니다. 봇 게이트웨이에만 넣고 다른 사람에게 주지 마세요. 새어 나갔다면 바로 새 토큰을 만드세요.",
        "bot_token_done" to "복사했습니다",
        "bot_rotate" to "새 토큰",
        "bot_revoke" to "토큰 폐기",
        "bot_delete" to "봇 삭제",
        "bot_token_off" to "토큰 없음 (폐기됨)",
        "bot_gateway_on" to "게이트웨이 연결됨",
        "bot_gateway_off" to "게이트웨이 없음",
        "bot_contacts" to "대화한 사람",
        "bot_reports" to "열린 신고",
        "bot_description" to "설명",
        "bot_commands" to "명령 (한 줄에 하나: /명령 설명)",
        "bot_save" to "저장",
        "bot_feature_privacy" to "그룹에서 자기에게 온 메시지만 받기 (bot.privacy_mode)",
        "bot_feature_groups" to "그룹에 추가될 수 있음 (bot.join_groups)",
        "bot_feature_inline" to "인라인 질의 (bot.inline)",
        "bot_feature_directory" to "봇 목록에 표시 (bot.directory)",
        "bot_feature_payments" to "봇 결제 (bot.payments)",
        "bot_feature_tips" to "봇 후원 (bot.tips)",
        "bot_feature_pay_out_points" to "포인트 지급 (bot.pay_out_points)",
        "bot_locked" to "잠김",
        "bot_search" to "봇 찾기 (이름 또는 @사용자이름)",
        "bot_none" to "찾은 봇이 없습니다",
        "bot_add" to "봇 추가 (@사용자이름)",
        "bot_block" to "봇 차단",
        "bot_privacy_note" to "이 봇은 그룹에서 자기에게 온 메시지(명령, 언급, 답장)만 받습니다.",
        "bot_reads_all_note" to "이 봇은 이 그룹의 모든 메시지를 받습니다.",
        "bot_answer_empty" to "봇이 받았습니다",
        "chat_bots_off" to "이 그룹은 봇을 허용하지 않습니다 (chat.bots)",
    )

    val en = mapOf(
        "bots" to "Bots",
        "bot_badge" to "bot",
        "bot_factory" to "Bot factory",
        "bot_factory_note" to "Tree runs no bots. A bot's maker runs it on their own server with the bot gateway. Whoever runs the gateway reads every message the bot receives.",
        "bot_username" to "Bot username (ends with bot)",
        "bot_create" to "Create",
        "bot_token" to "Bot token",
        "bot_token_note" to "This token is shown only now. Put it into the bot gateway and give it to nobody else. If it leaked, make a new token at once.",
        "bot_token_done" to "I copied it",
        "bot_rotate" to "New token",
        "bot_revoke" to "Revoke token",
        "bot_delete" to "Delete bot",
        "bot_token_off" to "No token (revoked)",
        "bot_gateway_on" to "Gateway connected",
        "bot_gateway_off" to "No gateway",
        "bot_contacts" to "People who talked to it",
        "bot_reports" to "Open reports",
        "bot_description" to "Description",
        "bot_commands" to "Commands (one per line: /command description)",
        "bot_save" to "Save",
        "bot_feature_privacy" to "In groups, only messages addressed to it (bot.privacy_mode)",
        "bot_feature_groups" to "Can be added to groups (bot.join_groups)",
        "bot_feature_inline" to "Inline queries (bot.inline)",
        "bot_feature_directory" to "Listed in the bot directory (bot.directory)",
        "bot_feature_payments" to "Bot payments (bot.payments)",
        "bot_feature_tips" to "Tips to bots (bot.tips)",
        "bot_feature_pay_out_points" to "Paying out points (bot.pay_out_points)",
        "bot_locked" to "locked",
        "bot_search" to "Find a bot (name or @username)",
        "bot_none" to "No bots found",
        "bot_add" to "Add a bot (@username)",
        "bot_block" to "Block bot",
        "bot_privacy_note" to "In groups this bot gets only messages addressed to it (commands, mentions, replies).",
        "bot_reads_all_note" to "This bot gets every message of this group.",
        "bot_answer_empty" to "The bot got it",
        "chat_bots_off" to "This group does not allow bots (chat.bots)",
    )
}
