package app.tree.shared

/** Texts of the device protections (Wave 1 items 7-10), merged into [Strings]. */
internal object DeviceStrings {
    val ko = mapOf(
        "wrong_pin" to "PIN이 틀렸습니다",
        "attempts_left" to "남은 시도",
        "pin_unavailable" to "PIN으로 열 수 없습니다. 비밀 문장으로 여세요.",
        "app_lock" to "앱 잠금",
        "pin" to "PIN (숫자 6자리 이상)",
        "pin_enable" to "PIN 켜기",
        "pin_disable" to "PIN 끄기 (비밀 문장으로만 열기)",
        "pin_unlock" to "PIN으로 열기",
        "pin_on" to "PIN 잠금 켜짐",
        "pin_note" to "PIN은 편하지만 비밀 문장보다 약합니다. 6자리 PIN은 100만 가지뿐이라, 기기 파일을 통째로 복사한 사람은 시간을 들이면 맞출 수 있습니다. 앱에서는 10번 틀리면 PIN이 지워지고 비밀 문장이 필요합니다. 휴대폰에서는 기기 보안 저장소의 비밀값이 함께 들어가 복사한 파일만으로는 맞출 수 없습니다. 컴퓨터에는 그런 저장소가 없습니다.",
        "bio_unlock" to "생체 인증으로 열기",
        "bio_enable" to "생체 인증 켜기",
        "bio_unavailable" to "이 기기에서는 생체 인증을 쓸 수 없습니다",
        "bio_prompt" to "트리 열기",
        "bio_note" to "데이터베이스 키를 기기 보안 저장소의 키로 감쌉니다. 그 키는 생체 인증을 통과해야만 쓸 수 있고, 지문이나 얼굴을 새로 등록하면 무효가 됩니다. 비밀 문장은 그대로 쓸 수 있습니다.",
        "search" to "메시지 검색",
        "search_none" to "찾은 메시지가 없습니다",
        "search_off" to "검색이 꺼져 있습니다 (user.search_index)",
        "search_note" to "검색 색인은 이 기기의 암호화된 데이터베이스 안에만 있습니다. 단어의 앞부분으로 찾습니다.",
        "note_incognito_desktop" to "컴퓨터에서는 효과가 없습니다. 키보드는 운영체제의 것이라 앱이 학습을 막을 수 없습니다. 안드로이드에서 작동합니다.",
        "note_blur_desktop" to "휴대폰 전용입니다 (최근 앱 화면).",
        "capture_active" to "켜짐: 이 시스템에서 이 창은 화면 캡처에서 빠집니다.",
        "capture_off" to "꺼짐: 다른 앱이 이 창을 캡처할 수 있습니다.",
        "capture_none" to "이 시스템에서는 쓸 수 없습니다: 앱이 자기 창을 화면 캡처에서 빼는 방법이 없습니다. 다른 앱과 시스템이 이 창을 캡처할 수 있습니다.",
        "notify_locked" to "새 소식이 있습니다",
        "notify_channel" to "메시지",
        "push_none" to "푸시 앱이 없습니다: 트리가 메모리에 있을 때 15분마다 확인합니다.",
        "push_on" to "푸시 알림 켜짐",
    )

    val en = mapOf(
        "wrong_pin" to "Wrong PIN",
        "attempts_left" to "attempts left",
        "pin_unavailable" to "The PIN cannot open the profile. Use your passphrase.",
        "app_lock" to "App lock",
        "pin" to "PIN (6 or more digits)",
        "pin_enable" to "Turn on PIN",
        "pin_disable" to "Turn off PIN (passphrase only)",
        "pin_unlock" to "Unlock with PIN",
        "pin_on" to "PIN unlock is on",
        "pin_note" to "A PIN is convenient but weaker than your passphrase. A 6-digit PIN has only a million values, so someone who copies the device's files can find it with enough time. In the app, 10 wrong PINs delete the PIN and the passphrase is needed. On a phone a secret from the device's secure storage goes into it as well, so the copied files alone are not enough. Computers have no such storage.",
        "bio_unlock" to "Unlock with biometrics",
        "bio_enable" to "Turn on biometric unlock",
        "bio_unavailable" to "Biometric unlock is not available on this device",
        "bio_prompt" to "Open Tree",
        "bio_note" to "The database key is wrapped by a key in the device's secure storage that works only after a biometric check and stops working when a new fingerprint or face is enrolled. The passphrase keeps working.",
        "search" to "Search messages",
        "search_none" to "No messages found",
        "search_off" to "Search is off (user.search_index)",
        "search_note" to "The search index is only inside this device's encrypted database. Words are found by their beginning.",
        "note_incognito_desktop" to "No effect on a computer: the keyboard belongs to the operating system, so an app cannot stop it from learning. Works on Android.",
        "note_blur_desktop" to "Phone only (the recent-apps view).",
        "capture_active" to "Active: on this system this window is left out of screen captures.",
        "capture_off" to "Off: other apps can capture this window.",
        "capture_none" to "Not available on this system: there is no way for an app to keep its window out of screen captures here. Other apps and the system can capture it.",
        "notify_locked" to "Something new arrived",
        "notify_channel" to "Messages",
        "push_none" to "No push app found: Tree checks every 15 minutes while it is in memory.",
        "push_on" to "Push wake-ups on",
    )
}
