package app.tree.shared

/** Texts of @gardenerbot, merged into [Strings]. */
internal object GardenerStrings {
    val ko = mapOf(
        "gardener_name" to "정원사",
        "gardener_about" to "봇과 스티커 팩을 만들어 주는 Tree 기본 봇",
        "gardener_hello" to "안녕하세요, 정원사예요.\n봇이나 스티커 팩을 만들고 관리해 드려요. 이 대화는 이 기기 안에서만 처리돼요.\n\n아래에서 고르거나 / 를 눌러 명령을 보세요.",
        "g_cmd_newbot" to "새 봇 만들기",
        "g_cmd_mybots" to "내 봇 목록",
        "g_cmd_token" to "새 토큰 받기 (예전 토큰은 바로 멈춰요)",
        "g_cmd_revoke" to "토큰 끄기",
        "g_cmd_setdescription" to "봇 소개 바꾸기",
        "g_cmd_setcommands" to "봇 명령어 목록 바꾸기",
        "g_cmd_setprivacy" to "그룹에서 자기를 부른 메시지만 받기 켜기·끄기",
        "g_cmd_setjoingroups" to "그룹에 들어갈 수 있게 하기 켜기·끄기",
        "g_cmd_setinline" to "인라인 모드 켜기·끄기",
        "g_cmd_setdirectory" to "봇 목록에 보이기 켜기·끄기",
        "g_cmd_deletebot" to "봇 지우기",
        "g_cmd_newpack" to "스티커 팩 만들기",
        "g_cmd_addpack" to "링크로 스티커 팩 추가",
        "g_cmd_mypacks" to "내 스티커 팩",
        "g_cmd_delpack" to "스티커 팩 빼기",
        "g_cmd_cancel" to "하던 것 그만두기",
        "g_cmd_help" to "명령어 보기",
        "g_unknown" to "무슨 말인지 모르겠어요. /help 로 명령어를 볼 수 있어요.",
        "g_cancelled" to "그만뒀어요.",
        "g_newbot_name" to "새 봇의 아이디를 정해 주세요. 영어 소문자·숫자·_ 로 5~32자, 끝은 bot 이어야 해요. 예: weather_bot",
        "g_bot_made" to "%s 를 만들었어요.\n\n아래 토큰을 봇 게이트웨이에만 넣으세요. 이 토큰이 있으면 누구나 봇을 움직일 수 있으니 절대 남에게 주지 마세요. 새어 나갔으면 /token 으로 바로 바꾸세요.",
        "g_bot_failed" to "봇을 만들지 못했어요.",
        "g_no_bots" to "아직 만든 봇이 없어요.",
        "g_no_such_bot" to "그런 봇이 없어요. /mybots 로 확인해 보세요.",
        "g_which_bot" to "어느 봇이요?",
        "g_token_on" to "토큰 켜짐",
        "g_token_off" to "토큰 꺼짐",
        "g_gateways" to "연결 %d",
        "g_token" to "%s 의 새 토큰이에요. 예전 토큰은 이제 쓸 수 없어요.",
        "g_revoked" to "토큰을 껐어요. 봇이 멈췄어요. 다시 쓰려면 /token",
        "g_ask_description" to "봇 소개를 보내 주세요.",
        "g_ask_commands" to "명령어를 한 줄에 하나씩 보내 주세요.\n예:\n/start 시작하기\n/weather 오늘 날씨",
        "g_saved" to "저장했어요.",
        "g_confirm_delete" to "정말 %s 를 지울까요? 맞으면 봇 아이디를 그대로 보내 주세요. 되돌릴 수 없어요.",
        "g_deleted" to "봇을 지웠어요.",
        "g_not_deleted" to "아이디가 달라서 지우지 않았어요.",
        "g_locked" to "이 설정은 바꿀 수 없어요.",
        "g_on" to "%s: 켰어요.",
        "g_off" to "%s: 껐어요.",
        "g_failed" to "잘 안 됐어요. 잠시 뒤에 다시 해 보세요.",
        "g_pack_title" to "스티커 팩 이름을 보내 주세요.",
        "g_pack_send_image" to "스티커로 쓸 사진을 보내 주세요 (클립 버튼). 다 넣었으면 /publish",
        "g_pack_emoji" to "이 스티커에 어울리는 이모지 하나를 보내 주세요.",
        "g_pack_added" to "스티커 %d개. 더 보내거나 /publish 로 마무리하세요.",
        "g_pack_full" to "한 팩에는 120개까지예요.",
        "g_pack_empty" to "팩에 스티커가 없어요.",
        "g_pack_made" to "‘%s’ 팩을 만들었어요. 이 링크를 친구에게 주면 같은 팩을 쓸 수 있어요.",
        "g_ask_link" to "스티커 팩 링크를 보내 주세요.",
        "g_pack_installed" to "스티커 팩을 추가했어요.",
        "g_no_packs" to "스티커 팩이 없어요.",
        "g_no_such_pack" to "그런 팩이 없어요.",
        "g_pack_removed" to "팩을 뺐어요.",
        "g_image_unexpected" to "사진은 스티커 팩을 만들 때 보내 주세요.",
        "g_copy" to "복사",
    )
    val en = mapOf(
        "gardener_name" to "Gardener",
        "gardener_about" to "Tree's own bot for making bots and sticker packs",
        "gardener_hello" to "Hi, I'm the Gardener.\nI make and look after your bots and sticker packs. This chat is handled on this device only.\n\nPick below, or tap / for commands.",
        "g_cmd_newbot" to "Make a new bot",
        "g_cmd_mybots" to "Your bots",
        "g_cmd_token" to "New token (the old one stops at once)",
        "g_cmd_revoke" to "Turn the token off",
        "g_cmd_setdescription" to "Change the bot's description",
        "g_cmd_setcommands" to "Change the bot's command list",
        "g_cmd_setprivacy" to "In groups, only messages addressed to it: on/off",
        "g_cmd_setjoingroups" to "Can be added to groups: on/off",
        "g_cmd_setinline" to "Inline mode: on/off",
        "g_cmd_setdirectory" to "Shown in the bot list: on/off",
        "g_cmd_deletebot" to "Delete a bot",
        "g_cmd_newpack" to "Make a sticker pack",
        "g_cmd_addpack" to "Add a sticker pack by link",
        "g_cmd_mypacks" to "Your sticker packs",
        "g_cmd_delpack" to "Remove a sticker pack",
        "g_cmd_cancel" to "Stop what we were doing",
        "g_cmd_help" to "Show commands",
        "g_unknown" to "I didn't get that. /help shows the commands.",
        "g_cancelled" to "Stopped.",
        "g_newbot_name" to "Choose the new bot's username: 5-32 of a-z, 0-9 and _, ending in bot. For example weather_bot",
        "g_bot_made" to "%s is ready.\n\nPut the token below into your bot gateway only. Anyone with it can run the bot: never share it. If it leaked, /token makes a new one.",
        "g_bot_failed" to "Couldn't make the bot.",
        "g_no_bots" to "You have no bots yet.",
        "g_no_such_bot" to "No such bot. See /mybots.",
        "g_which_bot" to "Which bot?",
        "g_token_on" to "token on",
        "g_token_off" to "token off",
        "g_gateways" to "%d gateways",
        "g_token" to "New token for %s. The old one no longer works.",
        "g_revoked" to "Token off; the bot stopped. /token to start again.",
        "g_ask_description" to "Send the bot's description.",
        "g_ask_commands" to "Send the commands, one per line.\nFor example:\n/start Start\n/weather Today's weather",
        "g_saved" to "Saved.",
        "g_confirm_delete" to "Really delete %s? If so, send its username exactly. This can't be undone.",
        "g_deleted" to "Bot deleted.",
        "g_not_deleted" to "That's not its username; nothing deleted.",
        "g_locked" to "This setting can't be changed.",
        "g_on" to "%s: on.",
        "g_off" to "%s: off.",
        "g_failed" to "That didn't work. Try again in a moment.",
        "g_pack_title" to "Send the sticker pack's name.",
        "g_pack_send_image" to "Send a picture for a sticker (paper clip). When done, /publish",
        "g_pack_emoji" to "Send one emoji that fits this sticker.",
        "g_pack_added" to "%d stickers. Send more or /publish.",
        "g_pack_full" to "A pack holds at most 120.",
        "g_pack_empty" to "The pack has no stickers.",
        "g_pack_made" to "Pack '%s' made. Give this link to friends so they can use it.",
        "g_ask_link" to "Send the sticker pack link.",
        "g_pack_installed" to "Sticker pack added.",
        "g_no_packs" to "No sticker packs.",
        "g_no_such_pack" to "No such pack.",
        "g_pack_removed" to "Pack removed.",
        "g_image_unexpected" to "Send pictures while making a sticker pack.",
        "g_copy" to "Copy",
    )
}
