package app.tree.shared

/** Texts of the group and community screens (wave 3), merged into [Strings]. */
internal object GroupStrings {
    val ko = mapOf(
        "topics" to "주제",
        "topic_main" to "전체 대화",
        "topic_new" to "새 주제",
        "topic_name" to "주제 이름",
        "topic_rename" to "이름 바꾸기",
        "topic_close" to "주제 닫기",
        "topic_reopen" to "다시 열기",
        "topic_closed" to "닫힘",
        "topic_unnamed" to "(이름 모르는 주제)",
        "roles" to "역할",
        "role_new" to "새 역할",
        "role_name" to "역할 이름",
        "role_color" to "색 (#rrggbb)",
        "role_delete" to "역할 삭제",
        "role_save" to "역할 저장",
        "role_give" to "역할 주기",
        "role_take" to "역할 빼기",
        "perm_pin" to "메시지 고정",
        "perm_delete" to "다른 사람 메시지 삭제",
        "perm_add" to "멤버 추가",
        "perm_topics" to "주제 관리",
        "admin_log" to "관리 기록",
        "admin_log_note" to "이 기기가 직접 본 관리 행동만 있습니다. 나중에 들어온 기기에는 그 전 기록이 없습니다.",
        "log_rename" to "이름 변경",
        "log_admin_add" to "관리자 지정",
        "log_admin_remove" to "관리자 해제",
        "log_feature" to "설정 변경",
        "log_role_create" to "역할 만듦",
        "log_role_update" to "역할 바꿈",
        "log_role_delete" to "역할 삭제",
        "log_role_assign" to "역할 줌",
        "log_role_unassign" to "역할 뺌",
        "log_restrict" to "발언 제한",
        "log_unrestrict" to "발언 제한 해제",
        "log_community_add" to "커뮤니티에 대화 추가",
        "log_community_remove" to "커뮤니티에서 대화 뺌",
        "log_add" to "멤버 추가",
        "log_remove" to "멤버 내보냄",
        "log_pin" to "고정",
        "log_unpin" to "고정 해제",
        "log_delete" to "메시지 삭제",
        "log_topic" to "주제 만듦/바꿈",
        "log_topic_close" to "주제 닫음",
        "log_topic_reopen" to "주제 다시 엶",
        "log_join_approve" to "참여 승인",
        "log_join_decline" to "참여 거절",
        "welcome" to "환영 메시지",
        "welcome_text" to "새 멤버에게 보일 글 (500자까지)",
        "welcome_save" to "저장",
        "welcome_notice" to "환영 메시지",
        "history_share" to "새 멤버에게 최근 대화 보여주기",
        "history_share_notice" to "새 멤버도 최근 대화를 봅니다",
        "history_share_note" to "멤버를 추가한 기기가 최근 메시지를 새 멤버에게 다시 보냅니다. 원래 서명은 함께 가지 않으므로 보낸 사람은 '공유한 사람'의 주장으로 표시됩니다.",
        "history_received" to "추가해 준 멤버가 최근 대화를 공유했습니다",
        "shared_by" to "공유한 사람",
        "join_requests" to "참여 요청",
        "join_request_notice" to "초대 링크로 참여 요청이 왔습니다",
        "approve" to "승인",
        "slow_mode" to "슬로 모드",
        "slow_mode_wait" to "다음 메시지까지 기다릴 시간(초)",
        "slow_mode_hidden" to "슬로 모드를 어긴 메시지를 숨겼습니다",
        "restrict" to "발언 제한",
        "restricted" to "발언 제한됨",
        "restricted_you" to "이 대화에서 읽기만 할 수 있습니다. 끝나는 때",
        "unrestrict" to "제한 풀기",
        "delete_for_everyone_mod" to "모두에게서 삭제 (관리)",
        "communities" to "커뮤니티",
        "community_new" to "새 커뮤니티",
        "community_name" to "커뮤니티 이름",
        "community_add_chat" to "이 대화를 커뮤니티에 추가",
        "community_remove_chat" to "커뮤니티에서 빼기",
        "community_join" to "참여 요청",
        "community_joined" to "참여 중",
        "community_join_asked" to "참여를 요청했습니다. 관리자 기기가 추가해 줍니다.",
        "successor_note" to "내가 나가면 다음 관리자",
        "group_tools" to "그룹 관리",
    )

    val en = mapOf(
        "topics" to "Topics",
        "topic_main" to "Main chat",
        "topic_new" to "New topic",
        "topic_name" to "Topic name",
        "topic_rename" to "Rename",
        "topic_close" to "Close topic",
        "topic_reopen" to "Reopen",
        "topic_closed" to "Closed",
        "topic_unnamed" to "(unknown topic)",
        "roles" to "Roles",
        "role_new" to "New role",
        "role_name" to "Role name",
        "role_color" to "Colour (#rrggbb)",
        "role_delete" to "Delete role",
        "role_save" to "Save role",
        "role_give" to "Give role",
        "role_take" to "Take role",
        "perm_pin" to "Pin messages",
        "perm_delete" to "Delete others' messages",
        "perm_add" to "Add members",
        "perm_topics" to "Manage topics",
        "admin_log" to "Admin log",
        "admin_log_note" to "Only the admin actions this device saw itself. A device that joined later has no earlier entries.",
        "log_rename" to "renamed the group",
        "log_admin_add" to "made admin",
        "log_admin_remove" to "removed as admin",
        "log_feature" to "changed setting",
        "log_role_create" to "created role",
        "log_role_update" to "changed role",
        "log_role_delete" to "deleted role",
        "log_role_assign" to "gave role to",
        "log_role_unassign" to "took role from",
        "log_restrict" to "restricted",
        "log_unrestrict" to "lifted restriction of",
        "log_community_add" to "added chat to community",
        "log_community_remove" to "removed chat from community",
        "log_add" to "added",
        "log_remove" to "removed",
        "log_pin" to "pinned",
        "log_unpin" to "unpinned",
        "log_delete" to "deleted a message of",
        "log_topic" to "created or renamed topic",
        "log_topic_close" to "closed topic",
        "log_topic_reopen" to "reopened topic",
        "log_join_approve" to "approved join of",
        "log_join_decline" to "declined join of",
        "welcome" to "Welcome message",
        "welcome_text" to "Text new members see (up to 500 characters)",
        "welcome_save" to "Save",
        "welcome_notice" to "Welcome",
        "history_share" to "Show new members the recent conversation",
        "history_share_notice" to "New members see the recent conversation",
        "history_share_note" to "The device that adds a member re-sends recent messages to them. The original signatures do not travel with them, so authors are shown as claims of the member who shared them.",
        "history_received" to "The member who added you shared the recent conversation",
        "shared_by" to "shared by",
        "join_requests" to "Join requests",
        "join_request_notice" to "Someone asked to join through your invite link",
        "approve" to "Approve",
        "slow_mode" to "Slow mode",
        "slow_mode_wait" to "Seconds until your next message",
        "slow_mode_hidden" to "A message that broke slow mode was hidden",
        "restrict" to "Restrict",
        "restricted" to "Restricted",
        "restricted_you" to "You can only read in this chat, until",
        "unrestrict" to "Lift restriction",
        "delete_for_everyone_mod" to "Delete for everyone (moderation)",
        "communities" to "Communities",
        "community_new" to "New community",
        "community_name" to "Community name",
        "community_add_chat" to "Add this chat to the community",
        "community_remove_chat" to "Remove from community",
        "community_join" to "Ask to join",
        "community_joined" to "Joined",
        "community_join_asked" to "Asked to join. An admin's device adds you.",
        "successor_note" to "If you leave, the next admin is",
        "group_tools" to "Group tools",
    )
}
