package app.tree.shared

/** Texts of public groups and channels and private channels (wave 4), merged into [Strings]. */
internal object PublicStrings {
    val ko = mapOf(
        "public_badge" to "공개",
        "public_group" to "공개 그룹",
        "public_channel" to "공개 채널",
        "public_spaces" to "공개 공간",
        "public_warning" to "공개 그룹과 채널은 종단간 암호화되지 않습니다. 서버와 누구나 글을 읽을 수 있고, 글과 함께 내 이름이 공개됩니다.",
        "public_search" to "이름 또는 @핸들로 찾기",
        "public_search_go" to "찾기",
        "public_none" to "찾은 공간이 없습니다",
        "public_create" to "공개 공간 만들기",
        "public_create_group" to "공개 그룹 만들기",
        "public_create_channel" to "공개 채널 만들기",
        "public_name" to "이름",
        "public_handle" to "@핸들 (영문 소문자, 숫자, _ 5~32자)",
        "public_description" to "설명",
        "public_join" to "구독",
        "public_leave" to "구독 취소",
        "public_members" to "구독자",
        "public_notify" to "새 글 알림",
        "public_post" to "글쓰기",
        "public_post_hint" to "모두에게 공개되는 글",
        "public_comment" to "댓글",
        "public_comments" to "댓글",
        "public_comment_hint" to "공개 댓글",
        "public_admins_only" to "이 채널은 관리자만 글을 씁니다",
        "public_admin_tools" to "관리 도구",
        "public_listing" to "공개 목록에 표시 (chat.public_listing)",
        "public_allow_comments" to "구독자 댓글 허용 (channel.comments)",
        "public_signatures" to "글쓴 관리자 이름 표시 (channel.signatures)",
        "public_slow_mode" to "천천히 모드 (chat.slow_mode)",
        "public_account" to "계정 id",
        "public_ban" to "차단",
        "public_unban" to "차단 해제",
        "public_make_admin" to "관리자로",
        "public_drop_admin" to "관리자 해제",
        "public_delete" to "삭제",
        "public_edit" to "수정",
        "public_report" to "신고",
        "public_reported" to "신고했습니다",
        "public_back" to "닫기",
        "public_unread" to "안 읽음",
        "public_banned" to "이 공간에서 차단되었습니다",
        "channel_new" to "비밀 채널 만들기",
        "channel_name" to "채널 이름",
        "channel_badge" to "채널",
        "channel_note" to "비밀 채널은 종단간 암호화됩니다. 관리자만 글을 쓰고 최대 1,000명까지 들어올 수 있습니다.",
        "channel_admins_only" to "관리자만 글을 쓸 수 있습니다",
        "channel_comment" to "댓글 달기",
        "channel_comments" to "댓글",
    )

    val en = mapOf(
        "public_badge" to "Public",
        "public_group" to "Public group",
        "public_channel" to "Public channel",
        "public_spaces" to "Public spaces",
        "public_warning" to "Public groups and channels are not end-to-end encrypted. The server and anyone can read the posts, and your name is published with what you post.",
        "public_search" to "Find by name or @handle",
        "public_search_go" to "Find",
        "public_none" to "Nothing found",
        "public_create" to "Create a public space",
        "public_create_group" to "Create public group",
        "public_create_channel" to "Create public channel",
        "public_name" to "Name",
        "public_handle" to "@handle (a-z, 0-9, _; 5 to 32)",
        "public_description" to "Description",
        "public_join" to "Subscribe",
        "public_leave" to "Unsubscribe",
        "public_members" to "subscribers",
        "public_notify" to "Notify me of new posts",
        "public_post" to "Post",
        "public_post_hint" to "A post everyone can read",
        "public_comment" to "Comment",
        "public_comments" to "Comments",
        "public_comment_hint" to "A public comment",
        "public_admins_only" to "Only admins post in this channel",
        "public_admin_tools" to "Admin tools",
        "public_listing" to "Show in the public directory (chat.public_listing)",
        "public_allow_comments" to "Subscribers may comment (channel.comments)",
        "public_signatures" to "Show the posting admin's name (channel.signatures)",
        "public_slow_mode" to "Slow mode (chat.slow_mode)",
        "public_account" to "Account id",
        "public_ban" to "Ban",
        "public_unban" to "Unban",
        "public_make_admin" to "Make admin",
        "public_drop_admin" to "Drop admin",
        "public_delete" to "Delete",
        "public_edit" to "Edit",
        "public_report" to "Report",
        "public_reported" to "Reported",
        "public_back" to "Close",
        "public_unread" to "unread",
        "public_banned" to "You are banned from this space",
        "channel_new" to "Create private channel",
        "channel_name" to "Channel name",
        "channel_badge" to "Channel",
        "channel_note" to "A private channel is end-to-end encrypted. Only admins post; up to 1,000 members.",
        "channel_admins_only" to "Only admins can post",
        "channel_comment" to "Comment",
        "channel_comments" to "Comments",
    )
}
