package app.tree.shared

/** Texts of QR codes, the scanner and the device-link code screen, merged into [Strings]. */
internal object QrStrings {
    val ko = mapOf(
        "qr_link_new_device" to "새 기기 연결 (QR 스캔)",
        "qr_new_device" to "새 기기입니다 — 내 계정에 연결",
        "qr_show_new" to "이미 쓰는 휴대폰에서 '새 기기 연결'을 누르고 이 QR 코드를 스캔하세요.",
        "qr_copy" to "링크 복사",
        "qr_copied" to "복사했습니다",
        "qr_add_friend" to "QR로 친구 추가",
        "qr_my_code" to "내 QR 코드 — 친구가 스캔하면 나를 추가합니다",
        "qr_scan_device" to "새 기기 화면의 QR 코드를 비추세요",
        "qr_scan_friend" to "친구의 QR 코드를 비추세요",
        "qr_not_tree" to "트리 코드가 아닙니다. 이 코드는 열지 않습니다.",
        "qr_wrong_device" to "친구 추가 코드입니다. 기기 연결 코드가 아닙니다.",
        "qr_wrong_friend" to "기기 연결 코드입니다. 친구 추가 코드가 아닙니다.",
        "qr_friend_added" to "친구를 추가했습니다",
        "safety_matched" to "안전 번호가 일치해요. 확인됨으로 표시했어요",
        "qr_safety_title" to "안전 번호 확인",
        "qr_scan_safety" to "상대 화면에 보이는 안전 번호 QR을 찍으세요.",
        "qr_wrong_safety" to "안전 번호 QR이 아니에요",
        "qr_torch" to "손전등",
        "qr_close" to "닫기",
        "qr_paste" to "또는 링크를 붙여 넣으세요",
        "qr_camera_why" to "QR 코드를 읽으려면 카메라가 필요합니다. 화면은 이 휴대폰 안에서만 읽고, 사진은 저장하거나 보내지 않습니다.",
        "qr_camera_allow" to "카메라 허용",
        "qr_camera_denied" to "카메라 권한이 없습니다. 휴대폰 설정에서 허용하거나, 아래에 링크를 붙여 넣으세요.",
        "qr_desktop_paste" to "컴퓨터에서는 카메라로 스캔하지 않습니다. 새 기기에 보이는 링크를 복사해 여기에 붙여 넣으세요.",
        "code_title" to "두 기기의 숫자를 비교하세요",
        "code_hold_both" to "두 기기를 모두 지금 직접 손에 들고 있을 때만 확인하세요.",
        "code_match" to "두 기기의 숫자가 같습니다",
        "code_differ" to "다름 / 내가 시작하지 않음",
        "code_other_too" to "다른 기기에서도 확인을 눌러야 연결됩니다.",
    )

    val en = mapOf(
        "qr_link_new_device" to "Link a new device (scan QR)",
        "qr_new_device" to "This is a new device — link to my account",
        "qr_show_new" to "On the phone you already use, tap \"Link a new device\" and scan this QR code.",
        "qr_copy" to "Copy link",
        "qr_copied" to "Copied",
        "qr_add_friend" to "Add friend by QR",
        "qr_my_code" to "My QR code — a friend who scans it adds me",
        "qr_scan_device" to "Point the camera at the QR code on the new device",
        "qr_scan_friend" to "Point the camera at your friend's QR code",
        "qr_not_tree" to "Not a Tree code. It will not be opened.",
        "qr_wrong_device" to "This is a friend code, not a device link code.",
        "qr_wrong_friend" to "This is a device link code, not a friend code.",
        "qr_friend_added" to "Friend added",
        "safety_matched" to "Safety numbers match. Marked as verified",
        "qr_safety_title" to "Verify safety number",
        "qr_scan_safety" to "Scan the safety number QR code on their screen.",
        "qr_wrong_safety" to "That is not a safety number code",
        "qr_torch" to "Light",
        "qr_close" to "Close",
        "qr_paste" to "Or paste the link",
        "qr_camera_why" to "Tree needs the camera to read QR codes. Frames are read on this phone only; no picture is saved or sent.",
        "qr_camera_allow" to "Allow camera",
        "qr_camera_denied" to "No camera permission. Allow it in the phone's settings, or paste the link below.",
        "qr_desktop_paste" to "The computer does not scan with a camera. Copy the link shown on the new device and paste it here.",
        "code_title" to "Compare the digits on both devices",
        "code_hold_both" to "Confirm only while you hold both devices yourself, right now.",
        "code_match" to "The digits match on both devices",
        "code_differ" to "Different / I did not start this",
        "code_other_too" to "Confirm on the other device too; only then is it linked.",
    )
}
