package app.tree.shared

/** Texts of the rich chat screens (wave 2 part A), merged into [Strings]. */
internal object RichStrings {
    val ko = mapOf(
        "pinned" to "고정된 메시지",
        "pin_msg" to "메시지 고정",
        "unpin_msg" to "고정 해제",
        "pin_24h" to "24시간",
        "pin_7d" to "7일",
        "pin_30d" to "30일",
        "pin_forever" to "계속",
        "poll" to "투표",
        "poll_new" to "투표 만들기",
        "poll_question" to "질문",
        "poll_options" to "선택지 (한 줄에 하나, 2~10개)",
        "poll_multi" to "여러 개 선택",
        "poll_anon" to "익명 (앱이 누가 골랐는지 보여주지 않음)",
        "poll_anon_note" to "익명 투표도 각 투표는 멤버들 기기에 보낸 사람이 확인된 채로 전달됩니다. 앱이 이름을 보여주지 않을 뿐입니다.",
        "poll_close" to "투표 마감",
        "poll_closed" to "마감됨",
        "poll_votes" to "표",
        "poll_retract" to "내 투표 취소",
        "schedule" to "예약 전송",
        "scheduled" to "예약된 메시지",
        "schedule_in" to "보낼 때",
        "schedule_note" to "예약 메시지는 이 기기에만 있습니다. 서버는 내용을 갖고 있지 않고 예약도 하지 않습니다. 그 시간에 앱이 켜져 있어야 하며, 아니면 다음 동기화 때 보내집니다.",
        "in_10m" to "10분 뒤",
        "in_1h" to "1시간 뒤",
        "tomorrow" to "내일 이 시간",
        "edit_text" to "수정",
        "cancel_action" to "취소",
        "forward" to "전달",
        "forward_to" to "어디로 전달할까요?",
        "forwarded" to "전달됨",
        "copy" to "복사",
        "remind_me" to "나중에 알림",
        "reminder" to "알림",
        "reminders" to "알림 예정",
        "export" to "대화 내보내기",
        "exported" to "내보낸 파일",
        "storage_clean_now" to "오래된 미디어 지금 정리",
        "storage_cleaned" to "정리한 파일",
        "open_file" to "열기",
    )

    val en = mapOf(
        "pinned" to "Pinned messages",
        "pin_msg" to "Pin message",
        "unpin_msg" to "Unpin",
        "pin_24h" to "24 hours",
        "pin_7d" to "7 days",
        "pin_30d" to "30 days",
        "pin_forever" to "Until unpinned",
        "poll" to "Poll",
        "poll_new" to "New poll",
        "poll_question" to "Question",
        "poll_options" to "Options (one per line, 2 to 10)",
        "poll_multi" to "Several choices",
        "poll_anon" to "Anonymous (apps do not show who chose what)",
        "poll_anon_note" to "In an anonymous poll every vote still reaches members' devices authenticated as its sender; the apps only do not show names.",
        "poll_close" to "Close poll",
        "poll_closed" to "Closed",
        "poll_votes" to "votes",
        "poll_retract" to "Take my vote back",
        "schedule" to "Schedule",
        "scheduled" to "Scheduled messages",
        "schedule_in" to "Send",
        "schedule_note" to "Scheduled messages stay on this device. The server neither holds them nor schedules anything: the app must be running at that time, or the next sync sends them.",
        "in_10m" to "In 10 minutes",
        "in_1h" to "In 1 hour",
        "tomorrow" to "Tomorrow, same time",
        "edit_text" to "Edit",
        "cancel_action" to "Cancel",
        "forward" to "Forward",
        "forward_to" to "Forward to which chat?",
        "forwarded" to "Forwarded",
        "copy" to "Copy",
        "remind_me" to "Remind me",
        "reminder" to "Reminder",
        "reminders" to "Upcoming reminders",
        "export" to "Export chat",
        "exported" to "Exported files",
        "storage_clean_now" to "Clean old media now",
        "storage_cleaned" to "Files cleaned",
        "open_file" to "Open",
    )
}
