package app.tree.shared

/** UI language. Korean first; English for everyone else. */
enum class Lang { KO, EN }

/** All UI text. Keys are English; missing Korean falls back to English. */
object Strings {
    var lang: Lang = if (java.util.Locale.getDefault().language == "ko") Lang.KO else Lang.EN

    private val ko = mapOf(
        "app" to "트리",
        "create" to "새 계정 만들기",
        "open" to "열기",
        "name" to "이름",
        "passphrase" to "비밀 문장 (기기 잠금)",
        "server" to "서버 주소",
        "chats" to "대화",
        "requests" to "요청함",
        "settings" to "설정",
        "new_group" to "새 대화",
        "invite" to "초대 (@아이디 또는 계정)",
        "send" to "보내기",
        "message" to "메시지",
        "accept" to "수락",
        "decline" to "거절",
        "block" to "차단",
        "report" to "신고",
        "safety" to "안전 번호",
        "verify" to "확인 완료",
        "recovery" to "복구 문구 만들기",
        "recovery_note" to "이 단어들을 종이에 적어 안전한 곳에 두세요. 지금 한 번만 보입니다. 이 단어를 가진 사람은 계정을 가져갈 수 있습니다.",
        "invite_link" to "초대 링크 만들기",
        "join" to "링크로 참여",
        "username" to "내 @아이디",
        "applied" to "적용",
        "released" to "해제",
        "locked" to "바꿀 수 없음",
        "release_pending" to "해제 예정일 (그때까지 계속 적용됨)",
        "option" to "옵션",
        "wrong_pass" to "비밀 문장이 틀렸거나 파일이 손상됐습니다",
        "key_changed" to "상대의 기기 키가 바뀌었습니다. 안전 번호를 다시 확인하세요.",
        "request_from" to "모르는 사람이 보낸 대화 요청",
        "edited" to "수정됨",
        "deleted" to "삭제된 메시지",
        "me" to "나",
        "attach" to "파일",
        "after_accept" to "수락하면 볼 수 있음",
        "group_notice" to "연락처에 없는 사람이 나를 그룹에 넣었습니다. 누가 있는지 확인하세요.",
        "typing" to "입력 중…",
        "read" to "읽음",
        "notes" to "나와의 채팅",
        "all" to "전체",
        "unread" to "안 읽음",
        "direct" to "1:1",
        "groups" to "그룹",
        "quiet" to "조용한 채팅방",
        "new_folder" to "새 폴더",
        "delete_account" to "계정 삭제",
        "delete_confirm" to "계정과 이 기기의 모든 대화가 지워지고 되돌릴 수 없습니다. 삭제할까요?",
        "save" to "저장",
        "group_settings" to "그룹 설정 (관리자)",
        "verified" to "확인됨",
        "compare" to "상대와 직접 만나거나 통화하며 이 숫자가 같은지 비교하세요.",
        "pending" to "보내는 중",
        "failed" to "보내지 못함",
        "retry" to "다시 보내기",
        "cancel_send" to "취소",
        "send_failed" to "메시지를 보내지 못했습니다. 다시 보내거나 취소하세요.",
        "pin" to "위에 고정",
        "unpin" to "고정 해제",
        "mute" to "알림 끄기",
        "unmute" to "알림 켜기",
        "muted" to "알림 꺼짐",
        "until" to "까지",
        "forever" to "계속",
        "archive" to "보관",
        "unarchive" to "보관 해제",
        "archived" to "보관된 대화",
        "back_to_list" to "대화 목록으로",
        "mark_unread" to "안 읽음으로 표시",
        "mark_read" to "읽음으로 표시",
        "leave" to "나가기",
        "leave_quietly" to "조용히 나가기 (나갔다는 알림 없이)",
        "silent" to "알림 없이 보내기",
        "not_contact" to "연락처 아님",
        "no_common_group" to "함께 있는 그룹 없음",
        "name_unverified" to "이름 확인 안 됨",
        "left" to "님이 나갔습니다",
        "removed" to "님이 내보내졌습니다",
        "username_link" to "내 아이디 링크 (QR 코드)",
        "reset_link" to "링크 새로 만들기 (예전 링크는 더 이상 안 됨)",
        "add_by_link" to "링크로 친구 추가",
        "added" to "친구로 추가했습니다",
        "menu" to "더보기",
        "draft" to "임시 저장",
        "link_new" to "기존 계정에 이 기기 연결",
        "link_show" to "이미 쓰는 기기에서 이 링크를 스캔하거나 붙여 넣으세요:",
        "link_scan" to "새 기기 연결 (링크 붙여 넣기)",
        "link_code" to "두 기기에 같은 숫자가 보이는지 확인하세요. 지금 두 기기를 모두 손에 들고 있을 때만 확인을 누르세요.",
        "link_match" to "숫자가 같음",
        "link_differ" to "다름 / 내가 시작하지 않음",
        "link_wait" to "다른 기기를 기다리는 중…",
        "link_done" to "연결됨",
        "link_cancelled" to "연결되지 않음",
        "devices" to "내 기기",
        "remove_device" to "기기 제거",
        "remove_device_asked" to "멤버가 자기 다른 기기를 이 대화에서 빼 달라고 합니다. 맞는지 확인한 뒤 관리자가 직접 빼 주세요.",
        "photo" to "사진",
        "edit" to "보내기 전에 편집",
        "crop" to "자르기",
        "draw" to "그리기",
        "text" to "글자",
        "blur" to "가리기",
        "rotate" to "돌리기",
        "undo" to "되돌리기",
        "original_stays" to "원본은 이 기기에만 남고, 편집한 사진만 위치·카메라 정보 없이 보내집니다.",
        "pause" to "일시정지",
        "resume" to "이어서",
        "uploading" to "올리는 중",
        "downloading" to "받는 중",
        "paused" to "멈춤",
        "save_as" to "다른 이름으로 저장",
        "downloaded" to "받음",
    ) + RichStrings.ko

    private val en = mapOf(
        "app" to "Tree",
        "create" to "Create account",
        "open" to "Open",
        "name" to "Name",
        "passphrase" to "Passphrase (device lock)",
        "server" to "Server URL",
        "chats" to "Chats",
        "requests" to "Requests",
        "settings" to "Settings",
        "new_group" to "New chat",
        "invite" to "Invite (@username or account)",
        "send" to "Send",
        "message" to "Message",
        "accept" to "Accept",
        "decline" to "Decline",
        "block" to "Block",
        "report" to "Report",
        "safety" to "Safety number",
        "verify" to "Mark verified",
        "recovery" to "Make recovery phrase",
        "recovery_note" to "Write these words on paper and keep them safe. They are shown only now. Whoever has them can take over the account.",
        "invite_link" to "Make invite link",
        "join" to "Join with link",
        "username" to "My @username",
        "applied" to "On",
        "released" to "Off",
        "locked" to "Cannot be changed",
        "release_pending" to "Release pending until (still on until then)",
        "option" to "Option",
        "wrong_pass" to "Wrong passphrase, or the file is damaged",
        "key_changed" to "A contact's device key changed. Compare the safety number again.",
        "request_from" to "Chat request from someone you don't know",
        "edited" to "edited",
        "deleted" to "Deleted message",
        "me" to "Me",
        "attach" to "File",
        "after_accept" to "visible after you accept",
        "group_notice" to "Someone who is not in your contacts added you to a group. Check who is in it.",
        "typing" to "typing…",
        "read" to "read",
        "notes" to "Note to self",
        "all" to "All",
        "unread" to "Unread",
        "direct" to "1:1",
        "groups" to "Groups",
        "quiet" to "Quiet chats",
        "new_folder" to "New folder",
        "delete_account" to "Delete account",
        "delete_confirm" to "Your account and every chat on this device are deleted. This cannot be undone. Delete?",
        "save" to "Save",
        "group_settings" to "Group settings (admins)",
        "verified" to "Verified",
        "compare" to "Compare these digits with the other person in person or on a call.",
        "pending" to "sending",
        "failed" to "not sent",
        "retry" to "Retry",
        "cancel_send" to "Cancel",
        "send_failed" to "A message could not be sent. Retry or cancel it.",
        "pin" to "Pin to top",
        "unpin" to "Unpin",
        "mute" to "Mute",
        "unmute" to "Unmute",
        "muted" to "Muted",
        "until" to "until",
        "forever" to "Until I unmute",
        "archive" to "Archive",
        "unarchive" to "Unarchive",
        "archived" to "Archived chats",
        "back_to_list" to "Back to chats",
        "mark_unread" to "Mark as unread",
        "mark_read" to "Mark as read",
        "leave" to "Leave",
        "leave_quietly" to "Leave quietly (no \"left\" message)",
        "silent" to "Send without sound",
        "not_contact" to "Not a contact",
        "no_common_group" to "No groups in common",
        "name_unverified" to "Name not verified",
        "left" to "left",
        "removed" to "was removed",
        "username_link" to "My username link (QR code)",
        "reset_link" to "Reset link (the old one stops working)",
        "add_by_link" to "Add friend by link",
        "added" to "Added to your contacts",
        "menu" to "More",
        "draft" to "Draft",
        "link_new" to "Link this device to an existing account",
        "link_show" to "On a device you already use, scan or paste this link:",
        "link_scan" to "Link a new device (paste its link)",
        "link_code" to "Check that both devices show the same digits. Confirm only while you hold both devices yourself.",
        "link_match" to "Digits match",
        "link_differ" to "Different / I did not start this",
        "link_wait" to "Waiting for the other device…",
        "link_done" to "Linked",
        "link_cancelled" to "Not linked",
        "devices" to "My devices",
        "remove_device" to "Remove device",
        "remove_device_asked" to "A member asks to remove another of their devices from this chat. Check it, then remove it yourself as an admin.",
        "photo" to "Photo",
        "edit" to "Edit before sending",
        "crop" to "Crop",
        "draw" to "Draw",
        "text" to "Text",
        "blur" to "Blur",
        "rotate" to "Rotate",
        "undo" to "Undo",
        "original_stays" to "The original stays on this device; only the edited picture is sent, without place or camera data.",
        "pause" to "Pause",
        "resume" to "Resume",
        "uploading" to "uploading",
        "downloading" to "downloading",
        "paused" to "paused",
        "save_as" to "Save as",
        "downloaded" to "downloaded",
    ) + RichStrings.en

    fun t(key: String): String = (if (lang == Lang.KO) ko[key] else null) ?: en[key] ?: key

    /** Every key exists in both languages (checked by a test). */
    fun missing(): Set<String> = (ko.keys - en.keys) + (en.keys - ko.keys)
}
